apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: cluster-config
spec:
  interval: 1m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: aks-wp-app-gitops
  path: ./workload/apps/dev
  prune: true
  wait: true
  timeout: 10m0s