---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: cluster-config
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: aks-wp-app-gitops
  path: ./workload/infrastructure/dev
  prune: true
  wait: true
  timeout: 10m0s