apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: cluster-config
spec:
  targetNamespace: wordpress
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "17.1.15"
  interval: 1h0m0s
  install:
    remediation:
      retries: 10
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml
  values:
    wordpressUsername: 'admin'
    wordpressPassword: 'admin'
    wordpressFirstName: 'admin'
    wordpressLastName: 'admin'
    wordpressBlogName: 'Wordpress in Azure AKS'
    wordpressEmail: 'ajoian@gmail.com'
    allowEmptyPassword: false
    allowOverrideNone: true
    replicaCount: 1
    pdb:
      create: true
      minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 1
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    mariadb:
      enabled: false
    externalDatabase:
      type: mysql
      host: server001.mysql.database.azure.com
      user: wpuser
      password: 'admin'
      database: wpdb
      port: 3306
      TableNamePrefix: wp0_
    wordpressScheme: https
    healthcheckHttps: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      tls: true
      certManager: true
      hostname: wordpress002.westus2.cloudapp.azure.com
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: aks-wp-letsencrypt-staging
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
    wordpressConfigureCache: true
    memcached:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi 
        limits:
          cpu: 250m
          memory: 128Mi
    # https://github.com/bitnami/charts/issues/16332
    # https://github.com/nextcloud/helm/issues/399
    livenessProbe:
      initialDelaySeconds: 60
      failureThreshold: 60
    readinessProbe:
      initialDelaySeconds: 60
      failureThreshold: 60
    startupProbe:
      initialDelaySeconds: 60
      failureThreshold: 60
    metrics:
      enabled: false