---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: cluster-config
spec:
  releaseName: nginx-ingress-controller
  targetNamespace: ingress
  chart:
    spec:
      chart: nginx-ingress-controller
      version: "~9.8.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
  interval: 1h0m0s
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    replicaCount: 1
    pdb:
      create: true
      minAvailable: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 128Mi
    defaultBackend:
      pdb:
        create: true
        minAvailable: 1
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 250m
          memory: 128Mi
    service:
      externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
        service.beta.kubernetes.io/azure-dns-label-name: "wordpress002"